version: '3'

services:
  backend:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: lambdaGrp2
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lambda-grp2?reWriteBatchedInserts=true
      - SPRING_DATASOURCE_USERNAME=grp2
      - SPRING_DATASOURCE_PASSWORD=grp2
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=grp2
      - POSTGRES_PASSWORD=grp2
      - POSTGRES_DB=lambda-grp2
volumes:
  pgdata: